### ISSUE TITLE
can 't run at win 10,could you help me?

### ISSUE THREAD

**Issue by zwlyn** [glouw/paperview#8]

**Comment by theblazehen** [comment]
Windows 10 isn't linux. You may wish to look into https://store.steampowered.com/app/431960/Wallpaper_Engine/ for windows

**Comment by nwxnk** [comment]
Since the core functionality is handled by SDL2 which is cross-platform, I made a Windows port of this project. If you want to, have a look: https://github.com/nwxnk/animwal

**Comment by glouw** [comment]
Give this one a shot too:
https://github.com/TrAyZeN/sdl-wallpaper

**Comment by abhijit-23blaze** [comment]
https://github.com/TrAyZeN/sdl-wallpaper ya try this it is good

**Comment by zwlyn** [comment]
after cmake . , how could I use it?
